# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  consolidate-data:
    cmds:
      - python src/scripts/consolidate_data.py
    desc: Run the consolidate data script
